/* Base PostgreSQL éphémère : aucune connexion au projet Supabase réel. */
const {PGlite}=require('@electric-sql/pglite');
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');

(async()=>{
 const db=new PGlite();let checks=0;
 const q=async(sql,params=[])=>db.query(sql,params);
 const scalar=async(sql,params=[])=>Object.values((await q(sql,params)).rows[0])[0];
 const ok=(value)=>{assert.ok(value);checks++;};
 const denied=async(sql,params=[],pattern=/CONSO_DENIED|permission denied/)=>{await assert.rejects(q(sql,params),pattern);checks++;};
 const login=async(email,role='authenticated')=>{
  await db.exec('reset role');
  await q("select set_config('request.jwt.claims',$1,false)",[JSON.stringify(email?{sub:randomUUID(),email}: {})]);
  await db.exec('set role '+role);
 };
 const state=()=>({app:'ConsoBingo',schema_version:1,case_id:'lea-pulse-v1',seed:2026,run_id:randomUUID(),answers:{},history:{},feedback:{},aids:{},ui:{},unlocked:[],finished_at:null});
 await db.exec(`
  create role anon;create role authenticated;create schema auth;
  create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;
  create function auth.uid() returns uuid language sql stable as $$select (auth.jwt()->>'sub')::uuid$$;
  grant usage on schema auth to public;
  create table public.swot_students(student_id text primary key,email text unique,first_name text,last_name text,campus text,group_name text,promotion text,active boolean);
  create table public.swot_teachers(email text primary key,first_name text,last_name text,is_admin boolean,active boolean);
  insert into swot_students values
    ('one','one@example.org','One','Test','Campus','A','2026',true),
    ('two','two@example.org','Two','Test','Campus','A','2026',true),
    ('inactive','inactive@example.org','Inactive','Test','Campus','B','2026',false);
  insert into swot_teachers values('teacher@example.org','Teacher','Test',true,true);
 `);
 const schema=fs.readFileSync(path.join(__dirname,'../sql/01_installation.sql'),'utf8');
 await db.exec(schema);await db.exec(schema);checks++;
 await login(null,'anon');
 ok(await scalar("select public.conso_can_login(' ONE@example.org ','student')"));
 ok(!await scalar("select public.conso_can_login('inactive@example.org','student')"));
 await denied('select * from conso_students');
 await denied('select * from conso_runs');
 await denied("select public.conso_identity('student')");
 await login('unknown@example.org');await denied("select public.conso_identity('student')");
 await login('one@example.org');
 ok((await scalar("select conso_identity('student')")).student_id==='one');
 await denied("select conso_identity('teacher')");
 await denied('select conso_dashboard()');
 await denied('select * from conso_runs');
 await denied('select * from conso_students');
 await denied('select conso_get_run($1)',['two']);
 await denied('select conso_archived_runs($1)',['two']);
 const sid=await scalar('select conso_open_session()');let g=state();
 let run=await scalar('select conso_claim_run($1,$2)',[sid,g]);ok(run.revision===0&&run.state.run_id===g.run_id);
 const save=async(session,revision,game,event,finish=false)=>scalar('select conso_save_run($1,$2,$3,$4,$5,$6)',[session,revision,game,[],event,finish]);
 const event=randomUUID();g.answers={ekb:{d1:0}};
 run=await save(sid,0,g,event);ok(run.revision===1);
 run=await save(sid,0,g,event);ok(run.revision===1);
 await denied('select conso_save_run($1,0,$2,$3,$4,false)',[sid,g,[],randomUUID()],/CONSO_CONFLICT/);
 await denied('select conso_save_run($1,1,$2,$3,$4,false)',[sid,{...g,seed:7},[],randomUUID()],/CONSO_INVALID/);
 await denied('select conso_save_run($1,1,$2,$3,$4,false)',[sid,{...g,unlocked:null},[],randomUUID()],/CONSO_INVALID/);
 const sid2=await scalar('select conso_open_session()');
 run=await scalar('select conso_claim_run($1)',[sid2]);ok(run.state.answers.ekb.d1===0&&run.revision===1);
 await denied('select conso_save_run($1,1,$2,$3,$4,false)',[sid,g,[],randomUUID()],/CONSO_LEASE/);
 g.finished_at=new Date().toISOString();run=await save(sid2,1,g,randomUUID(),true);ok(!!run.completed_at);
 g.answers.ekb.a1=2;run=await save(sid2,2,g,randomUUID());ok(run.revision===3&&run.state.answers.ekb.a1===2);
 await denied("select conso_reserve_mail('two','completion','')");
 await denied("select conso_reserve_mail('one','invitation','c')");
 let job=await scalar("select conso_reserve_mail('one','completion','')");ok(job.allowed&&job.recipient==='one@example.org');
 ok(!(await scalar("select conso_reserve_mail('one','completion','')")).allowed);
 await denied('select conso_mark_mail($1,$2,$3)',[job.job_id,randomUUID(),'sent']);
 ok(await scalar('select conso_mark_mail($1,$2,$3)',[job.job_id,job.token,'sent']));
 ok((await scalar('select conso_mails()')).every(j=>!('token' in j)&&j.student_id==='one'));
 await login('two@example.org');
 await denied('select conso_claim_run($1)',[sid2]);
 await denied('select conso_get_run($1)',['one']);
 await denied('select conso_archived_runs($1)',['one']);
 ok((await scalar('select conso_mails()')).length===0);
 await login('teacher@example.org');
 ok((await scalar("select conso_identity('teacher')")).role==='teacher');
 ok((await scalar('select conso_dashboard()')).length===2);
 ok((await scalar('select conso_get_run($1)',['one'])).state.run_id===g.run_id);
 await denied('select conso_open_session()');
 job=await scalar("select conso_reserve_mail('two','invitation','batch1')");ok(job.allowed&&job.recipient==='two@example.org');
 await denied("select conso_reserve_mail('two','result','batch2')",[],/CONSO_NOT_FINISHED/);
 await login('one@example.org');
 const newState=state();run=await scalar('select conso_restart($1,$2,$3)',[sid2,3,newState]);
 ok(run.cycle===2&&run.revision===4&&!run.completed_at);
 run=await scalar('select conso_restart($1,$2,$3)',[sid2,3,newState]);ok(run.cycle===2&&run.revision===4);
 const archives=await scalar('select conso_archived_runs()');ok(archives.length===1&&archives[0].state.run_id===g.run_id);
 await db.exec('reset role');
 await db.exec("update swot_students set group_name='C' where student_id='one'");
 await login('one@example.org');ok((await scalar("select conso_identity('student')")).group_name==='C');
 await db.exec('reset role');await db.exec("update swot_students set active=false where student_id='one'");
 await login('one@example.org');await denied('select conso_get_run()');
 await denied('select conso_claim_run($1)',[sid2]);
 await db.exec('reset role');await db.exec("update swot_students set active=true where student_id='one'");
 await login('one@example.org');ok(await scalar('select conso_close_session($1)',[sid2]));
 await denied('select conso_claim_run($1)',[sid2]);
 console.log(`${checks} vérifications PostgreSQL réussies : annuaire partagé, autorisations, reprise, conflits, archives et réservation des courriels.`);
 await db.close();
})().catch(e=>{console.error(e);process.exit(1);});
