/* Interface locale. Le moteur Python fournit toutes les évaluations. */
(()=>{'use strict';
const root=document.getElementById('consobingo-bd');
let C=null,G=null,args={},edit=0,pending=null,queued=null,dirty=false,lastSync=0,drag=null;
const L={confirmRestart:false,selected:null,token:null,bonus:null,calc:'',calcResult:'',hints:{},flash:'',stale:new Set()};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const art=(n,cls='')=>`<div class="cb-art ${n==='exposure'?'cb-exposure':''} ${cls}" ${n==='exposure'?'':`style="--cb-x:${(n%3)*50}%;--cb-y:${Math.floor(n/3)*50}%"`} aria-hidden="true"></div>`;
const action=(name,label,primary=false,extra='')=>`<button type="button" class="${primary?'cb-primary':''}" data-act="${name}" ${extra}>${label}</button>`;
const heading=(k,title,desc)=>`<div class="cb-eyebrow">${k}</div><h2>${title}</h2><p class="cb-lead">${desc}</p>`;
const guide=s=>`<div class="cb-guide"><span class="cb-step">↗</span><div>${s}</div></div>`;
const rowBy=(arr,id,key='id')=>arr.find(x=>x[key]===id);
const ordered=(arr,ids,key='id')=>ids.map(id=>rowBy(arr,id,key)).filter(Boolean);
const selected=(a,b)=>a===b?'selected':'';
const opt=(id,label,current)=>`<option value="${esc(id)}" ${selected(String(id),String(current))}>${esc(label)}</option>`;
const options=(dict,current,ids=Object.keys(dict))=>'<option value="">Choisir…</option>'+ids.map(id=>opt(id,dict[id],current)).join('');
const status=k=>G.summary.find(x=>x.id===k);
const fresh=k=>!L.stale.has(k)&&G.fresh_feedback.includes(k);
const complete=k=>!L.stale.has(k)&&status(k)?.complete;
function post(type,more={}){parent.postMessage({isStreamlitMessage:true,type,...more},'*');}
function height(){requestAnimationFrame(()=>post('streamlit:setFrameHeight',{height:Math.ceil(document.body.scrollHeight+8)}));}
function syncText(){if(args.demo)return dirty?'Démo · modifications dans cet onglet':'Démo · session de test';if(args.sync_error)return 'Sauvegarde à réessayer';return pending?'Enregistrement…':dirty?'Modifications en attente':'Sauvegarde confirmée';}
function changed(section){edit++;dirty=true;if(section){L.stale.add(section);if(section.startsWith('rule_'))L.stale.add('selection_'+section.slice(5));}L.flash='';root.querySelectorAll('[data-live-feedback]').forEach(el=>{if(!section||el.dataset.liveFeedback===section)el.remove();});updateStatus();}
function updateStatus(){const el=root.querySelector('[data-sync]');if(el)el.textContent=syncText();}
function emit(kind='checkpoint',section=''){
 if(!G||args.disabled)return;
 if(pending){if(kind!=='checkpoint')queued={kind,section};return;}
 const nonce=crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;
 pending={nonce,edit,kind,section};
 post('streamlit:setComponentValue',{dataType:'json',value:{nonce,run_id:G.run_id,kind,section,answers:structuredClone(G.answers),ui:structuredClone(G.ui),expression:L.calc}});
 lastSync=Date.now();updateStatus();if(kind!=='checkpoint')render();
}
function isBusy(){return args.disabled||(pending&&pending.kind!=='checkpoint');}
function footerButtons(section,next){return `<div class="cb-actions">${action('check','Vérifier mon raisonnement',true,`data-section="${section}"`)}${action('hint','Un indice',false,`data-section="${section}"`)}${next?`<button type="button" class="cb-quiet cb-next" data-go="${next[0]}">${next[1]} →</button>`:''}</div>${L.hints[section]?guide(esc(L.hints[section])):''}${feedback(section)}`;}
function feedback(key){if(!fresh(key))return '';const f=G.feedback[key];if(!f)return '';const errors=f.items.filter(i=>!i.ok);return `<section class="cb-feedback ${f.complete?'cb-success':''}" data-live-feedback="${key}" aria-live="polite"><h3>${f.complete?'Les liens sont cohérents.':'Quelques points à reprendre.'}</h3><p>${esc(f.note)}</p>${f.extra?`<p>${esc(f.extra)}</p>`:''}${errors.length?`<ul>${errors.map(i=>`<li><strong>${esc(i.label)}</strong> : ${esc(i.detail)}</li>`).join('')}</ul>`:''}<details class="cb-explanations"><summary>Comprendre chaque réponse</summary><ul>${f.items.map(i=>`<li>${i.ok?'✓':'À revoir'} · <strong>${esc(i.label)}</strong><br>${esc(i.detail)}</li>`).join('')}</ul></details>${!key.startsWith('selection_')?`<div class="cb-actions">${action('solution','Consulter et appliquer le corrigé',false,`data-section="${key}"`)}</div>`:''}</section>`;}
function nav(){const pages=['story','attitude','table','rules','numbers','bonus','end'];const names=['La BD','L’attitude','Les offres','Les règles','Les chiffres','Bonus','Mon bilan'];const explored=G.summary.filter(s=>s.checked).length;return `<header class="cb-top"><button type="button" class="cb-brand" data-go="home">Conso<span>Bingo</span> ✳</button><span class="cb-beta">Autoévaluation</span><span class="cb-progress">${explored} activité${explored>1?'s':''} explorée${explored>1?'s':''}</span></header><nav class="cb-nav" aria-label="Les missions">${pages.map((p,i)=>`<button type="button" data-go="${p}" ${p===G.ui.screen?'aria-current="step"':''}><span class="cb-num">${i===5?'★':i+1}</span>${names[i]}</button>`).join('')}</nav>`;}
function home(){return `<div class="cb-hero"><div><div class="cb-eyebrow">Une histoire à lire entre les lignes</div><h1>Léa se remet<br>en mouvement.</h1><p>Léa, 24 ans, vient de commencer un emploi de bureau. Elle veut retrouver de l’énergie et s’inscrire dans une <strong>salle de sport</strong>. Trois offres retiennent son attention.</p><p class="cb-muted">Tu étudies son parcours pour aider Pulse, une enseigne de salles de gym, à comprendre les décisions de ses clients. Les informations sont dispersées et certaines ne sont pas utiles à son choix.</p><div class="cb-actions"><button type="button" class="cb-primary" data-go="story">Ouvrir la BD →</button><span class="cb-small cb-muted">En solo · à ton rythme</span></div></div><div class="cb-cover">${art(0)}${art(1)}${art(2)}${art(5)}<div class="cb-cover-note">Observe. Relie. Compare. Explique.</div></div></div><div class="cb-two"><div class="cb-notebook" style="margin-top:0"><h3>Un carnet pour progresser</h3><p>Tu peux essayer, demander un indice, consulter le corrigé et recommencer. Le bilan t’aide à repérer ce que tu comprends et ce qui reste à travailler.</p></div><div class="cb-notebook" style="margin-top:0"><h3>Une partie que tu peux reprendre</h3><p>Les réponses et l’ordre des documents sont conservés à la sauvegarde. Les bulles et les choix répondent immédiatement à tes clics.</p></div></div>`;}
function story(){const mode=G.ui.mode==='factors'?'factors':'ekb',A=G.answers[mode],labels=mode==='ekb'?C.stages:C.factor_labels,ids=mode==='ekb'?[0,1,2,3,4,5]:G.orders.factors;let s=heading('Mission 01 · Observer','Les cases sont dans le désordre.','Reconstruis le parcours, puis repère ce qui influence Léa. Une même phrase peut avoir plusieurs fonctions.');s+=`<div class="cb-tabs">${['ekb','factors'].map((m,i)=>`<button type="button" data-mode="${m}" aria-pressed="${mode===m}">${i+1}. ${m==='ekb'?'Parcours EKB':'Facteurs d’influence'}</button>`).join('')}</div>`;s+=guide(mode==='ekb'?'<strong>Clique une bulle et attribue-lui une étape.</strong> Certaines phrases renseignent surtout le contexte et peuvent rester sans annotation.':'<strong>Repère les influences individuelles, situationnelles ou sociales et culturelles.</strong> Puis relie deux indices différents à leurs effets sur le choix.');s+=`<div class="cb-row" style="justify-content:space-between;margin-bottom:12px"><span class="cb-tag">${mode==='ekb'?'Surligneur EKB':'Surligneur facteurs'}</span><span class="cb-small cb-muted">${Object.keys(A).length} passages annotés</span></div><div class="cb-board">${ordered(C.panels,G.orders.panels,'letter').map(p=>`<article class="cb-panel"><header class="cb-panel-head"><span>${esc(p.title)}</span><span class="cb-letter">${p.letter}</span></header>${art(p.art,'cb-panel-art')}<div class="cb-dialogue">${p.ids.map(id=>{const c=rowBy(C.clues,id),v=A[id],f=fresh(mode)?G.feedback[mode].items.find(x=>x.key===id):null;return `<div><button type="button" class="cb-bubble ${v!==undefined?'cb-marked':''} ${f&&v!==undefined?(f.ok?'cb-right':'cb-wrong'):''}" data-clue="${id}" aria-expanded="${L.selected===id}"><span class="cb-speaker">${esc(c.speaker)}</span>${esc(c.text)}${v!==undefined?`<span class="cb-annotation">↳ ${labels[v]}</span>`:''}</button>${L.selected===id?`<div class="cb-choose"><p>Ce passage renseigne…</p>${ids.map(i=>`<button type="button" data-classify="${id},${i}">${labels[i]}</button>`).join('')}<button type="button" data-classify="${id},remove">Retirer l’annotation</button><button type="button" data-act="close-clue">Fermer</button></div>`:''}</div>`;}).join('')}</div></article>`).join('')}</div>`;
if(mode==='factors'){const found=C.clues.filter(c=>A[c.id]!==undefined);s+=`<div class="cb-notebook"><h3>Explique deux influences différentes</h3><p class="cb-small cb-muted">Utilise les passages que tu as annotés. Deux caractéristiques personnelles différentes peuvent déjà se combiner.</p><div class="cb-links">${G.answers.influence_links.map((link,i)=>`<div class="cb-linkbox"><label for="influence-clue-${i}">Indice dans la BD</label><select id="influence-clue-${i}" data-effect="${i},clue"><option value="">Choisir un passage…</option>${found.map(c=>opt(c.id,c.text,link.clue)).join('')}</select><label for="influence-effect-${i}">Ce que cela change dans le choix</label><select id="influence-effect-${i}" data-effect="${i},effect">${options(C.effects,link.effect,G.orders.effects)}</select></div>`).join('')}</div></div>`;}
s+=`<div class="cb-actions">${action('check','Vérifier mes annotations',true,`data-section="${mode}"`)}${action('hint','Un indice',false,`data-section="${mode}"`)}${mode==='ekb'?'<button type="button" class="cb-quiet cb-next" data-mode="factors">Chercher les influences →</button>':'<button type="button" class="cb-quiet cb-next" data-go="attitude">Du message à l’attitude →</button>'}</div>${L.hints[mode]?guide(esc(L.hints[mode])):''}${feedback(mode)}`;return s;}
function attitude(){let s=heading('Mission 02 · Reconstruire','Du message à l’attitude','Replace chaque vignette devant l’opération qu’elle illustre. Le décor seul ne suffit pas à identifier ce qui se passe.');s+=guide('<strong>Utilise ↑ et ↓ ou fais glisser les vignettes.</strong> Observe le regard de Léa et ce qu’elle fait du message.');s+=`<div class="cb-mcg">${G.answers.attitude.map((id,i)=>{const m=rowBy(C.attitude,id);const f=fresh('attitude')?G.feedback.attitude.items[i]:null;return `<div class="cb-mcg-row" data-drop="${i}"><div class="cb-stage-label"><span>${i+1}</span>${C.attitude_stages[i]}</div><article class="cb-strip ${f?(f.ok?'cb-right':'cb-wrong'):''}" draggable="true" data-drag="${i}">${art(m.art)}<div><small>${esc(m.who)}</small><p>${esc(m.text)}</p></div><div class="cb-arrows"><button type="button" data-move="${i},-1" aria-label="Monter : ${esc(m.who)}" ${i===0?'disabled':''}>↑</button><button type="button" data-move="${i},1" aria-label="Descendre : ${esc(m.who)}" ${i===4?'disabled':''}>↓</button></div></article></div>`;}).join('')}</div>`;return s+footerButtons('attitude',['table','Construire le tableau']);}
function tokens(text){return esc(text).replace(/\d+(?:[ \u202f]\d{3})*(?:[.,]\d+)?/g,n=>`<button type="button" class="cb-token" data-number="${n.replace(/[ \u202f]/g,'')}" aria-label="Collecter ${n}">${n}</button>`);}
function calculator(){return `<details class="cb-calculator"><summary>Calculatrice</summary><div class="cb-row"><input type="text" data-calc aria-label="Expression à calculer" placeholder="Saisis ton calcul" value="${esc(L.calc)}">${action('calculate','Calculer')}<output data-calc-result aria-live="polite">${esc(L.calcResult)}</output></div><p class="cb-small cb-muted">Nombres, +, −, * ou / et parenthèses.</p></details>`;}
function documents(docs,order){return `<div class="cb-two">${ordered(docs,order).map(d=>`<article class="cb-source">${art(d.art)}<div><h3>${esc(d.title)}</h3>${d.lines.map(t=>`<p>${tokens(t)}</p>`).join('')}</div></article>`).join('')}</div>`;}
function tableView(){const A=G.answers;let s=heading('Mission 03 · Construire','Qu’est-ce qui compte pour cette cliente ?','Compose le tableau utile à Léa. Les renseignements proviennent de plusieurs documents et ne sont pas tous décisifs.');s+=guide('<strong>Choisis jusqu’à quatre en-têtes et relie chacun à un besoin exprimé.</strong> Puis renseigne les cases. Un nombre collecté peut être une composante à recalculer.');s+=documents(C.documents,G.orders.documents);s+=`<h3 style="margin-top:23px">Les colonnes de ton tableau</h3><div class="cb-pool">${G.orders.criteria.map(id=>`<button type="button" data-criterion="${id}" aria-pressed="${A.criteria.includes(id)}">${A.criteria.includes(id)?'✓ ': '+ '}${C.criteria[id].label}</button>`).join('')}</div><div class="cb-evidence">${A.criteria.map(id=>`<label>${C.criteria[id].label}<select data-evidence="${id}" aria-label="Justifier : ${C.criteria[id].label}"><option value="">Quel passage justifie ce critère ?</option>${C.needs.map(n=>opt(n.id,n.text,A.criteria_evidence[id])).join('')}</select></label>`).join('')}</div><div class="cb-tray" aria-live="polite">${L.token!==null?`Nombre en main : <strong>${esc(L.token)}</strong> · Clique sa destination.`:'Clique un nombre dans les documents ou saisis directement les valeurs.'}</div>`;
if(A.criteria.length)s+=`<div class="cb-table-wrap"><table><thead><tr><th scope="col">Salle</th>${A.criteria.map(id=>`<th scope="col">${C.criteria[id].label}<small>${C.criteria[id].unit}</small></th>`).join('')}</tr></thead><tbody>${C.offers.map(o=>`<tr><th scope="row">${o.name}</th>${A.criteria.map(id=>`<td><input type="text" inputmode="decimal" data-cell="${o.id}_${id}" aria-label="${o.name} · ${C.criteria[id].label}" value="${esc(A.table[o.id+'_'+id]??'')}"></td>`).join('')}</tr>`).join('')}</tbody></table></div>`;else s+='<div class="cb-scratch">Choisis tes en-têtes pour faire apparaître les colonnes.</div>';
return s+calculator()+footerButtons('table',['rules','Tester les règles de décision']);}
function offerButton(o,rid,counter=false){const selectedOffers=G.answers.rules[rid][counter?'counter_keep':'keep'];let p={...o};if(counter&&C.rules[rid].changes?.[o.id])Object.assign(p,C.rules[rid].changes[o.id]);return `<button type="button" class="cb-offer" data-offer="${rid},${o.id},${counter?'counter_keep':'keep'}" aria-pressed="${selectedOffers.includes(o.id)}"><strong>${p.name}</strong><span class="cb-price">${p.fee} € <small>/ mois</small></span><span class="cb-spec">${p.travel} min depuis le bureau</span><span class="cb-spec">Fermeture à ${p.close} h</span><span class="cb-spec">${p.coach} séance${p.coach>1?'s':''} accompagnée${p.coach>1?'s':''} incluse${p.coach>1?'s':''}</span><span class="cb-select-label">${selectedOffers.includes(o.id)?'✓ Conservée':'+ Conserver'}</span></button>`;}
function rules(){const rid=G.ui.rule in C.rules?G.ui.rule:G.orders.rules[0],v=G.answers.rules[rid],r=C.rules[rid],n=G.orders.rules.indexOf(rid);let s=heading('Mission 04 · Expérimenter','Les mêmes offres, plusieurs raisonnements','Conserve les salles qui passent la règle, puis identifie le modèle et teste ce qui se passe lorsqu’une information change.');s+=`<div class="cb-tabs">${G.orders.rules.map((id,i)=>`<button type="button" data-rule="${id}" aria-pressed="${rid===id}">Situation ${i+1}</button>`).join('')}</div><div class="cb-speech"><span class="cb-speaker">Léa · une façon possible de décider</span>« ${esc(r.text)} »</div><p class="cb-small cb-muted">Données de référence corrigées · Conserve toutes les offres qui passent.</p><div class="cb-offers">${G.orders.offers[rid].map(id=>offerButton(rowBy(C.offers,id),rid)).join('')}</div><div class="cb-actions">${action('check','Tester ma sélection',true,`data-section="selection_${rid}"`)}</div>${feedback('selection_'+rid)}`;
if(G.unlocked.includes(rid)){s+=`<div class="cb-notebook"><h3>Comment s’appelle ce raisonnement ?</h3><div class="cb-rule-names">${G.orders.models[rid].map(id=>`<button type="button" data-model="${rid},${id}" aria-pressed="${v.model===id}">${C.models[id]}</button>`).join('')}</div></div><h3 style="margin-top:24px">Une information change…</h3><p class="cb-lead">${esc(r.counter_text)}</p><div class="cb-offers">${G.orders.offers[rid].map(id=>offerButton(rowBy(C.offers,id),rid,true)).join('')}</div>`;s+=footerButtons('rule_'+rid,n===2?['numbers','Ouvrir le dossier des chiffres']:null);if(n<2)s+=`<div class="cb-actions"><button type="button" data-rule="${G.orders.rules[n+1]}">Situation suivante →</button></div>`;}
return s;}
function numbers(){const mid=G.ui.metric,m=rowBy(C.metrics,mid)||C.metrics[0],A=G.answers.metrics[m.id];let s=heading('Mission 05 · Mesurer','Un mois plus tard, chez Pulse','La responsable te confie ses notes. Retrouve les données utiles, identifie les populations concernées et calcule les indicateurs.');s+=documents(C.metric_documents,G.orders.metric_documents);s+=`<div class="cb-tabs">${C.metrics.map(x=>`<button type="button" data-metric="${x.id}" aria-pressed="${m.id===x.id}">${x.name}</button>`).join('')}</div>`;
if(m.id==='nps'){const totals={prom:0,pass:0,det:0};Object.entries(A.groups).forEach(([id,g])=>{if(C.survey[id])totals[g]+=C.survey[id].count;});s+=`<div class="cb-notebook"><h3>Enquête : « Recommanderiez-vous Pulse ? »</h3><p class="cb-small cb-muted">Les réponses sont sur une échelle de 0 à 10. Constitue les trois groupes à partir de ce relevé.</p><div class="cb-survey">${G.orders.survey.map(id=>{const row=C.survey[id];return `<label><strong>Note ${row.note}</strong><span>${row.count} réponses</span><select data-survey="${id}" aria-label="Catégorie de la note ${row.note}">${options(C.survey_groups,A.groups[id])}</select></label>`;}).join('')}</div><p class="cb-small" style="margin-top:12px">Ton regroupement : ${totals.prom} promoteurs · ${totals.pass} passifs · ${totals.det} détracteurs.</p></div>`;}
s+=`<section class="cb-kpi-work"><h3>${m.name}${m.id==='ltv'?' simplifiée':''}</h3><div class="cb-tray">${L.token!==null?`Nombre collecté : <strong>${esc(L.token)}</strong>`:'Repère les nombres utiles, puis saisis ton résultat.'}</div><div class="cb-kpi-fields">${m.fields.map(([f,label])=>`<label>${label}<input type="text" inputmode="decimal" data-metric-field="${f}" aria-label="${label}" value="${esc(A.data[f]??'')}"></label>`).join('')}</div><label class="cb-result-input">Mon résultat <input type="text" inputmode="decimal" data-metric-result aria-label="Résultat ${m.name}" value="${esc(A.result)}"><strong>${m.unit}</strong></label>${calculator()}</section>`;return s+footerButtons('metric_'+m.id,['bonus','Conseiller Pulse']);}
function bonus(){let s=heading('Bonus · Conseiller','Deux actions, deux obstacles à traiter.','La responsable de Pulse peut lancer deux actions. Construis deux chaînes cohérentes à partir des indices sur Léa. Plusieurs combinaisons peuvent se défendre.');s+=guide('<strong>Clique un emplacement pour choisir une carte.</strong> Tu peux aussi faire glisser une carte sur un emplacement de même nature.');for(let i=0;i<2;i++){const a=G.answers.bonus[i];s+=`<h3>Action ${i+1}</h3><div class="cb-chain">${[['clue','Indice observé'],['objective','Objectif'],['action','Moyen proposé']].map(([field,label])=>{let text=field==='clue'?rowBy(C.bonus_clues,a[field])?.text:field==='objective'?C.objectives[a[field]]:C.actions[a[field]];return `<button type="button" data-slot="${i},${field}" aria-pressed="${L.bonus?.i===i&&L.bonus?.field===field}"><strong>${label}</strong>${esc(text||'Choisir une carte…')}</button>`;}).join('')}</div>`;if(L.bonus?.i===i){let field=L.bonus.field,dict=field==='clue'?Object.fromEntries(C.bonus_clues.map(c=>[c.id,c.text])):field==='objective'?C.objectives:C.actions,order=field==='clue'?G.orders.bonus_clues:field==='objective'?G.orders.objectives:G.orders.actions;s+=`<div class="cb-choice-bank"><p>Choisis ${field==='clue'?'l’indice':field==='objective'?'l’objectif':'l’action'} qui construit ton raisonnement.</p>${order.map(id=>`<button type="button" draggable="true" data-bonus-card="${field},${id}" data-bonus-choice="${i},${field},${id}">${esc(dict[id])}</button>`).join('')}</div>`;}}
return s+footerButtons('bonus',['end','Voir mon bilan']);}
function end(){const blocks=[['Parcours EKB',['ekb'],'story','ekb'],['Influences',['factors'],'story','factors'],['Traitement du message',['attitude'],'attitude'],['Comparaison',['table'],'table'],['Règles de décision',Object.keys(C.rules).map(k=>'rule_'+k),'rules'],['Indicateurs',['nps','churn','retention','ltv'].map(k=>'metric_'+k),'numbers'],['Conseiller Pulse',['bonus'],'bonus']];let s=heading('Mon carnet · Autoévaluation','Ce que tu comprends, ce que tu peux reprendre','Les indices et les corrigés font partie de l’apprentissage. Tu peux continuer à modifier tes réponses et rejouer.');s+=`<div class="cb-bingo">${blocks.map(([title,keys,page,mode])=>{const done=keys.every(complete);return `<section class="cb-stamp ${done?'cb-stamped':''}"><span class="cb-tag">${done?'Liens cohérents':'À explorer ou à reprendre'}</span><strong>${title}</strong><ul>${keys.map(k=>{const x=status(k);return `<li>${esc(x.label)} : ${L.stale.has(k)?'réponses modifiées':esc(x.status)}${x.attempts?` · ${x.attempts} essai${x.attempts>1?'s':''}`:''}</li>`;}).join('')}</ul><button type="button" data-go="${page}" ${mode?`data-enter-mode="${mode}"`:''}>Reprendre →</button></section>`;}).join('')}</div><div class="cb-actions">${action('finish',G.finished_at?'Actualiser mon bilan':'Enregistrer mon bilan de fin de parcours',true)}${action('save','Sauvegarder maintenant')}${action('restart',L.confirmRestart?'Confirmer la nouvelle partie':'Rejouer avec un nouvel ordre')}</div><p class="cb-lead">Après enregistrement, ton bilan personnel peut être téléchargé sous le jeu. Les missions restent accessibles.</p>`;return s;}
function render(){if(!G||!C)return;const opened=[...root.querySelectorAll('details[open]')].map(el=>el.className);const active=document.activeElement;const focus=active&&root.contains(active)?{tag:active.tagName,label:active.getAttribute('aria-label'),data:{...active.dataset}}:null;const views={home,story,attitude,table:tableView,rules,numbers,bonus,end};const view=views[G.ui.screen]||home;root.innerHTML=nav()+`<main class="cb-main">${isBusy()?'<div class="cb-wait" role="status">'+(args.disabled?'Recharge la sauvegarde pour reprendre cette partie.':'Vérification et sauvegarde…')+'</div>':''}${L.flash?`<div class="cb-error" role="alert">${esc(L.flash)}</div>`:''}${view()}</main><footer class="cb-footer"><span>ConsoBingo 1.0 · Cas fictif</span><span class="cb-sync" data-sync aria-live="polite">${syncText()}</span><button type="button" data-act="save">Sauvegarder</button><button type="button" data-act="leave">${args.demo?'Quitter la démo':'Se déconnecter'}</button></footer>`;
root.querySelectorAll('details').forEach(el=>{if(opened.includes(el.className))el.open=true;});
if(isBusy())root.querySelectorAll('button,input,select').forEach(e=>e.disabled=true);
if(focus){let next;if(focus.data.classify){const id=focus.data.classify.split(',')[0];next=root.querySelector(`[data-clue="${id}"]`);}else if(focus.label){next=[...root.querySelectorAll('[aria-label]')].find(e=>e.tagName===focus.tag&&e.getAttribute('aria-label')===focus.label&&!e.disabled);}else{const entries=Object.entries(focus.data);if(entries.length)next=[...root.querySelectorAll(focus.tag)].find(e=>entries.every(([k,v])=>e.dataset[k]===v)&&!e.disabled);}next?.focus({preventScroll:true});}
height();}
function inputField(el){if(el.hasAttribute('data-cell')){G.answers.table[el.dataset.cell]=el.value;changed('table');}
else if(el.hasAttribute('data-metric-field')){G.answers.metrics[G.ui.metric].data[el.dataset.metricField]=el.value;changed('metric_'+G.ui.metric);}
else if(el.hasAttribute('data-metric-result')){G.answers.metrics[G.ui.metric].result=el.value;changed('metric_'+G.ui.metric);}
else if(el.hasAttribute('data-calc')){L.calc=el.value;L.calcResult='';const o=root.querySelector('[data-calc-result]');if(o)o.textContent='';}}
root.addEventListener('input',e=>{if(G&&!isBusy()&&e.target.matches('input'))inputField(e.target);});
root.addEventListener('change',e=>{if(!G||isBusy())return;const el=e.target,d=el.dataset;if(d.effect){const [i,field]=d.effect.split(',');G.answers.influence_links[+i][field]=el.value;changed('factors');}
else if(d.evidence){G.answers.criteria_evidence[d.evidence]=el.value;changed('table');}
else if(d.survey){if(el.value)G.answers.metrics.nps.groups[d.survey]=el.value;else delete G.answers.metrics.nps.groups[d.survey];changed('metric_nps');}
else return;render();});
root.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.hasAttribute('data-calc')){e.preventDefault();emit('calculate');}});
function setBonus(i,field,id){G.answers.bonus[i][field]=id;changed('bonus');L.bonus=field==='clue'?{i,field:'objective'}:field==='objective'?{i,field:'action'}:null;render();if(L.bonus)root.querySelector(`[data-slot="${i},${L.bonus.field}"]`)?.focus({preventScroll:true});}
root.addEventListener('click',e=>{if(!G||isBusy())return;const input=e.target.closest('input');if(input&&(input.hasAttribute('data-cell')||input.hasAttribute('data-metric-field')||input.hasAttribute('data-metric-result'))&&L.token!==null){input.value=L.token;L.token=null;inputField(input);render();return;}
const b=e.target.closest('button');if(!b||!root.contains(b))return;const d=b.dataset;L.flash='';
if(d.go){G.ui.screen=d.go;if(d.enterMode)G.ui.mode=d.enterMode;L.selected=null;L.token=null;L.bonus=null;changed();emit();render();root.querySelector('.cb-main')?.scrollIntoView({block:'start'});return;}
if(d.mode){G.ui.mode=d.mode;L.selected=null;changed();render();return;}
if(d.clue){L.selected=L.selected===d.clue?null:d.clue;render();return;}
if(d.classify){const [id,v]=d.classify.split(',');if(v==='remove')delete G.answers[G.ui.mode][id];else G.answers[G.ui.mode][id]=+v;changed(G.ui.mode);L.selected=null;render();return;}
if(d.move){const [i,delta]=d.move.split(',').map(Number),j=i+delta;if(j>=0&&j<5){[G.answers.attitude[i],G.answers.attitude[j]]=[G.answers.attitude[j],G.answers.attitude[i]];changed('attitude');render();}return;}
if(d.criterion){const list=G.answers.criteria;if(list.includes(d.criterion))G.answers.criteria=list.filter(x=>x!==d.criterion);else if(list.length<4)list.push(d.criterion);else{L.flash='Choisis au maximum quatre critères. Tu peux retirer un en-tête pour le remplacer.';render();return;}changed('table');render();return;}
if(d.number!==undefined){L.token=L.token===d.number?null:d.number;render();return;}
if(d.rule){G.ui.rule=d.rule;changed();render();return;}
if(d.offer){const [rid,id,field]=d.offer.split(','),a=G.answers.rules[rid];a[field]=a[field].includes(id)?a[field].filter(x=>x!==id):[...a[field],id];changed('rule_'+rid);render();return;}
if(d.model){const [rid,id]=d.model.split(',');G.answers.rules[rid].model=id;changed('rule_'+rid);render();return;}
if(d.metric){G.ui.metric=d.metric;L.token=null;changed();render();return;}
if(d.slot){const [i,field]=d.slot.split(',');L.bonus={i:+i,field};render();return;}
if(d.bonusChoice){const [i,field,id]=d.bonusChoice.split(',');setBonus(+i,field,id);return;}
switch(d.act){case 'close-clue':L.selected=null;render();break;
case 'check':case 'hint':case 'solution':emit(d.act,d.section);break;
case 'save':emit();break;
case 'finish':emit('finish');break;
case 'restart':if(L.confirmRestart)emit('restart');else{L.confirmRestart=true;render();}break;
case 'leave':emit('leave');break;
case 'calculate':emit('calculate');break;}
});
root.addEventListener('dragstart',e=>{if(isBusy())return;const n=e.target.closest('[data-drag],[data-bonus-card]');if(!n)return;drag=n.dataset.drag!==undefined?{type:'attitude',i:+n.dataset.drag}:{type:'bonus',field:n.dataset.bonusCard.split(',')[0],id:n.dataset.bonusCard.split(',')[1]};e.dataTransfer.setData('text/plain',JSON.stringify(drag));e.dataTransfer.effectAllowed='move';});
root.addEventListener('dragover',e=>{if(drag&&e.target.closest('[data-drop],[data-slot]')&&!isBusy()){e.preventDefault();e.dataTransfer.dropEffect='move';}});
root.addEventListener('drop',e=>{if(!drag||isBusy())return;const row=e.target.closest('[data-drop]'),slot=e.target.closest('[data-slot]');if(row&&drag.type==='attitude'){e.preventDefault();const [it]=G.answers.attitude.splice(drag.i,1);G.answers.attitude.splice(+row.dataset.drop,0,it);changed('attitude');render();}else if(slot&&drag.type==='bonus'){const [i,field]=slot.dataset.slot.split(',');if(field===drag.field){e.preventDefault();setBonus(+i,field,drag.id);}}drag=null;});
root.addEventListener('dragend',()=>{drag=null;});
window.addEventListener('message',event=>{
 if(event.source!==parent||event.data?.type!=='streamlit:render')return;
 const incoming=event.data.args;if(!incoming?.catalog||!incoming?.state)return;
 const flagsChanged=args.disabled!==incoming.disabled||args.sync_error!==incoming.sync_error;args=incoming;C=incoming.catalog;const next=incoming.state;
 document.documentElement.style.colorScheme=event.data.theme?.base==='dark'?'dark':'light';
 if(!G||G.run_id!==next.run_id){G=structuredClone(next);edit=0;pending=null;queued=null;dirty=false;L.stale.clear();L.hints={};L.selected=null;L.token=null;L.bonus=null;L.confirmRestart=false;L.calc='';L.calcResult='';L.flash='';lastSync=Date.now();render();return;}
 if(pending&&incoming.ack===pending.nonce){
  const sent=pending;const localAnswers=G.answers,localUi=G.ui;
  G=structuredClone(next);
  if(edit!==sent.edit){G.answers=localAnswers;G.ui=localUi;}else{L.stale.clear();dirty=!!args.sync_error;}
  if(sent.kind==='hint')L.hints[sent.section]=incoming.message||'';
  if(sent.kind==='calculate')L.calcResult=incoming.message||'';
  if(incoming.error)L.flash=incoming.error;
  pending=null;render();
  if(sent.kind==='check'||sent.kind==='solution')root.querySelector(`[data-live-feedback="${sent.section}"]`)?.scrollIntoView({block:'nearest'});
  if(queued){const q=queued;queued=null;emit(q.kind,q.section);}
  return;
 }
 // Un rafraîchissement du parent ne doit pas écraser une saisie locale en attente.
 if(!pending&&!dirty){G=structuredClone(next);render();}else if(flagsChanged)render();else updateStatus();
});
new ResizeObserver(()=>height()).observe(root);
setInterval(()=>{if(G&&dirty&&!pending&&Date.now()-lastSync>=15000&&!document.hidden)emit();},1000);
window.addEventListener('beforeunload',()=>{if(G&&dirty&&!pending)emit();});
window.addEventListener('resize',height);
post('streamlit:componentReady',{apiVersion:1});
})();
